// flow-typed signature: ef846379a619270b7f9599c6b4d26c61
// flow-typed version: <<STUB>>/cron-parser_v^2.6.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cron-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cron-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cron-parser/lib/date' {
  declare module.exports: any;
}

declare module 'cron-parser/lib/expression' {
  declare module.exports: any;
}

declare module 'cron-parser/lib/parser' {
  declare module.exports: any;
}

declare module 'cron-parser/test/31_of_month' {
  declare module.exports: any;
}

declare module 'cron-parser/test/bug' {
  declare module.exports: any;
}

declare module 'cron-parser/test/expression' {
  declare module.exports: any;
}

declare module 'cron-parser/test/increment_on_first_iteration' {
  declare module.exports: any;
}

declare module 'cron-parser/test/parser' {
  declare module.exports: any;
}

declare module 'cron-parser/test/timezone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cron-parser/lib/date.js' {
  declare module.exports: $Exports<'cron-parser/lib/date'>;
}
declare module 'cron-parser/lib/expression.js' {
  declare module.exports: $Exports<'cron-parser/lib/expression'>;
}
declare module 'cron-parser/lib/parser.js' {
  declare module.exports: $Exports<'cron-parser/lib/parser'>;
}
declare module 'cron-parser/test/31_of_month.js' {
  declare module.exports: $Exports<'cron-parser/test/31_of_month'>;
}
declare module 'cron-parser/test/bug.js' {
  declare module.exports: $Exports<'cron-parser/test/bug'>;
}
declare module 'cron-parser/test/expression.js' {
  declare module.exports: $Exports<'cron-parser/test/expression'>;
}
declare module 'cron-parser/test/increment_on_first_iteration.js' {
  declare module.exports: $Exports<'cron-parser/test/increment_on_first_iteration'>;
}
declare module 'cron-parser/test/parser.js' {
  declare module.exports: $Exports<'cron-parser/test/parser'>;
}
declare module 'cron-parser/test/timezone.js' {
  declare module.exports: $Exports<'cron-parser/test/timezone'>;
}
