// flow-typed signature: 430e49f80c1cf7e4d0fa443dec379b1e
// flow-typed version: <<STUB>>/react-native-testfairy_v^2.13.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-testfairy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-testfairy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-testfairy/index' {
  declare module.exports: $Exports<'react-native-testfairy'>;
}
declare module 'react-native-testfairy/index.js' {
  declare module.exports: $Exports<'react-native-testfairy'>;
}
