// flow-typed signature: 50f19e0b376c713781e88d4dc881031a
// flow-typed version: <<STUB>>/pretty-format_v^25.1.0/flow_v0.105.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pretty-format/build-es5' {
  declare module.exports: any;
}

declare module 'pretty-format/build/collections' {
  declare module.exports: any;
}

declare module 'pretty-format/build' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/AsymmetricMatcher' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ConvertAnsi' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/DOMCollection' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/DOMElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/Immutable' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/lib/escapeHTML' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/lib/markup' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ReactElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ReactTestComponent' {
  declare module.exports: any;
}

declare module 'pretty-format/build/types' {
  declare module.exports: any;
}

declare module 'pretty-format/perf/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pretty-format/build-es5/index' {
  declare module.exports: $Exports<'pretty-format/build-es5'>;
}
declare module 'pretty-format/build-es5/index.js' {
  declare module.exports: $Exports<'pretty-format/build-es5'>;
}
declare module 'pretty-format/build/collections.js' {
  declare module.exports: $Exports<'pretty-format/build/collections'>;
}
declare module 'pretty-format/build/index' {
  declare module.exports: $Exports<'pretty-format/build'>;
}
declare module 'pretty-format/build/index.js' {
  declare module.exports: $Exports<'pretty-format/build'>;
}
declare module 'pretty-format/build/plugins/AsymmetricMatcher.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/AsymmetricMatcher'>;
}
declare module 'pretty-format/build/plugins/ConvertAnsi.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ConvertAnsi'>;
}
declare module 'pretty-format/build/plugins/DOMCollection.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/DOMCollection'>;
}
declare module 'pretty-format/build/plugins/DOMElement.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/DOMElement'>;
}
declare module 'pretty-format/build/plugins/Immutable.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/Immutable'>;
}
declare module 'pretty-format/build/plugins/lib/escapeHTML.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/lib/escapeHTML'>;
}
declare module 'pretty-format/build/plugins/lib/markup.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/lib/markup'>;
}
declare module 'pretty-format/build/plugins/ReactElement.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ReactElement'>;
}
declare module 'pretty-format/build/plugins/ReactTestComponent.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ReactTestComponent'>;
}
declare module 'pretty-format/build/types.js' {
  declare module.exports: $Exports<'pretty-format/build/types'>;
}
declare module 'pretty-format/perf/test.js' {
  declare module.exports: $Exports<'pretty-format/perf/test'>;
}
